// Code generated by easyjson for marshaling/unmarshaling. DO NOT EDIT.

package core

import (
	json "encoding/json"
	easyjson "github.com/mailru/easyjson"
	jlexer "github.com/mailru/easyjson/jlexer"
	jwriter "github.com/mailru/easyjson/jwriter"
	time "time"
)

// suppress unused package warning
var (
	_ *json.RawMessage
	_ *jlexer.Lexer
	_ *jwriter.Writer
	_ easyjson.Marshaler
)

func easyjsonF8e6253dDecodeGithubComGoParkMailRu20232UmlautModel(in *jlexer.Lexer, out *Complaint) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "id":
			out.Id = int(in.Int())
		case "reporter_user_id":
			out.ReporterUserId = int(in.Int())
		case "reported_user_id":
			out.ReportedUserId = int(in.Int())
		case "complaint_type_id":
			out.ComplaintTypeId = int(in.Int())
		case "complaint_text":
			if in.IsNull() {
				in.Skip()
				out.ComplaintText = nil
			} else {
				if out.ComplaintText == nil {
					out.ComplaintText = new(string)
				}
				*out.ComplaintText = string(in.String())
			}
		case "created_at":
			if in.IsNull() {
				in.Skip()
				out.CreatedAt = nil
			} else {
				if out.CreatedAt == nil {
					out.CreatedAt = new(time.Time)
				}
				if data := in.Raw(); in.Ok() {
					in.AddError((*out.CreatedAt).UnmarshalJSON(data))
				}
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjsonF8e6253dEncodeGithubComGoParkMailRu20232UmlautModel(out *jwriter.Writer, in Complaint) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"id\":"
		out.RawString(prefix[1:])
		out.Int(int(in.Id))
	}
	{
		const prefix string = ",\"reporter_user_id\":"
		out.RawString(prefix)
		out.Int(int(in.ReporterUserId))
	}
	{
		const prefix string = ",\"reported_user_id\":"
		out.RawString(prefix)
		out.Int(int(in.ReportedUserId))
	}
	{
		const prefix string = ",\"complaint_type_id\":"
		out.RawString(prefix)
		out.Int(int(in.ComplaintTypeId))
	}
	{
		const prefix string = ",\"complaint_text\":"
		out.RawString(prefix)
		if in.ComplaintText == nil {
			out.RawString("null")
		} else {
			out.String(string(*in.ComplaintText))
		}
	}
	{
		const prefix string = ",\"created_at\":"
		out.RawString(prefix)
		if in.CreatedAt == nil {
			out.RawString("null")
		} else {
			out.Raw((*in.CreatedAt).MarshalJSON())
		}
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v Complaint) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjsonF8e6253dEncodeGithubComGoParkMailRu20232UmlautModel(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v Complaint) MarshalEasyJSON(w *jwriter.Writer) {
	easyjsonF8e6253dEncodeGithubComGoParkMailRu20232UmlautModel(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *Complaint) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjsonF8e6253dDecodeGithubComGoParkMailRu20232UmlautModel(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *Complaint) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjsonF8e6253dDecodeGithubComGoParkMailRu20232UmlautModel(l, v)
}
