// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v4.25.1
// source: admin.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	Admin_GetFeedbackStatistic_FullMethodName       = "/proto.Admin/GetFeedbackStatistic"
	Admin_GetRecommendationStatistic_FullMethodName = "/proto.Admin/GetRecommendationStatistic"
	Admin_CreateFeedback_FullMethodName             = "/proto.Admin/CreateFeedback"
	Admin_CreateRecommendation_FullMethodName       = "/proto.Admin/CreateRecommendation"
	Admin_CreateFeedFeedback_FullMethodName         = "/proto.Admin/CreateFeedFeedback"
	Admin_GetNextComplaint_FullMethodName           = "/proto.Admin/GetNextComplaint"
	Admin_DeleteComplaint_FullMethodName            = "/proto.Admin/DeleteComplaint"
	Admin_AcceptComplaint_FullMethodName            = "/proto.Admin/AcceptComplaint"
)

// AdminClient is the client API for Admin service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type AdminClient interface {
	GetFeedbackStatistic(ctx context.Context, in *AdminEmpty, opts ...grpc.CallOption) (*FeedbackStatistic, error)
	GetRecommendationStatistic(ctx context.Context, in *AdminEmpty, opts ...grpc.CallOption) (*RecommendationStatistic, error)
	CreateFeedback(ctx context.Context, in *Feedback, opts ...grpc.CallOption) (*AdminEmpty, error)
	CreateRecommendation(ctx context.Context, in *Recommendation, opts ...grpc.CallOption) (*AdminEmpty, error)
	CreateFeedFeedback(ctx context.Context, in *Recommendation, opts ...grpc.CallOption) (*AdminEmpty, error)
	GetNextComplaint(ctx context.Context, in *AdminEmpty, opts ...grpc.CallOption) (*Complaint, error)
	DeleteComplaint(ctx context.Context, in *Complaint, opts ...grpc.CallOption) (*AdminEmpty, error)
	AcceptComplaint(ctx context.Context, in *Complaint, opts ...grpc.CallOption) (*AdminEmpty, error)
}

type adminClient struct {
	cc grpc.ClientConnInterface
}

func NewAdminClient(cc grpc.ClientConnInterface) AdminClient {
	return &adminClient{cc}
}

func (c *adminClient) GetFeedbackStatistic(ctx context.Context, in *AdminEmpty, opts ...grpc.CallOption) (*FeedbackStatistic, error) {
	out := new(FeedbackStatistic)
	err := c.cc.Invoke(ctx, Admin_GetFeedbackStatistic_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *adminClient) GetRecommendationStatistic(ctx context.Context, in *AdminEmpty, opts ...grpc.CallOption) (*RecommendationStatistic, error) {
	out := new(RecommendationStatistic)
	err := c.cc.Invoke(ctx, Admin_GetRecommendationStatistic_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *adminClient) CreateFeedback(ctx context.Context, in *Feedback, opts ...grpc.CallOption) (*AdminEmpty, error) {
	out := new(AdminEmpty)
	err := c.cc.Invoke(ctx, Admin_CreateFeedback_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *adminClient) CreateRecommendation(ctx context.Context, in *Recommendation, opts ...grpc.CallOption) (*AdminEmpty, error) {
	out := new(AdminEmpty)
	err := c.cc.Invoke(ctx, Admin_CreateRecommendation_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *adminClient) CreateFeedFeedback(ctx context.Context, in *Recommendation, opts ...grpc.CallOption) (*AdminEmpty, error) {
	out := new(AdminEmpty)
	err := c.cc.Invoke(ctx, Admin_CreateFeedFeedback_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *adminClient) GetNextComplaint(ctx context.Context, in *AdminEmpty, opts ...grpc.CallOption) (*Complaint, error) {
	out := new(Complaint)
	err := c.cc.Invoke(ctx, Admin_GetNextComplaint_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *adminClient) DeleteComplaint(ctx context.Context, in *Complaint, opts ...grpc.CallOption) (*AdminEmpty, error) {
	out := new(AdminEmpty)
	err := c.cc.Invoke(ctx, Admin_DeleteComplaint_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *adminClient) AcceptComplaint(ctx context.Context, in *Complaint, opts ...grpc.CallOption) (*AdminEmpty, error) {
	out := new(AdminEmpty)
	err := c.cc.Invoke(ctx, Admin_AcceptComplaint_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AdminServer is the server API for Admin service.
// All implementations must embed UnimplementedAdminServer
// for forward compatibility
type AdminServer interface {
	GetFeedbackStatistic(context.Context, *AdminEmpty) (*FeedbackStatistic, error)
	GetRecommendationStatistic(context.Context, *AdminEmpty) (*RecommendationStatistic, error)
	CreateFeedback(context.Context, *Feedback) (*AdminEmpty, error)
	CreateRecommendation(context.Context, *Recommendation) (*AdminEmpty, error)
	CreateFeedFeedback(context.Context, *Recommendation) (*AdminEmpty, error)
	GetNextComplaint(context.Context, *AdminEmpty) (*Complaint, error)
	DeleteComplaint(context.Context, *Complaint) (*AdminEmpty, error)
	AcceptComplaint(context.Context, *Complaint) (*AdminEmpty, error)
	mustEmbedUnimplementedAdminServer()
}

// UnimplementedAdminServer must be embedded to have forward compatible implementations.
type UnimplementedAdminServer struct {
}

func (UnimplementedAdminServer) GetFeedbackStatistic(context.Context, *AdminEmpty) (*FeedbackStatistic, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetFeedbackStatistic not implemented")
}
func (UnimplementedAdminServer) GetRecommendationStatistic(context.Context, *AdminEmpty) (*RecommendationStatistic, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetRecommendationStatistic not implemented")
}
func (UnimplementedAdminServer) CreateFeedback(context.Context, *Feedback) (*AdminEmpty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateFeedback not implemented")
}
func (UnimplementedAdminServer) CreateRecommendation(context.Context, *Recommendation) (*AdminEmpty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateRecommendation not implemented")
}
func (UnimplementedAdminServer) CreateFeedFeedback(context.Context, *Recommendation) (*AdminEmpty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateFeedFeedback not implemented")
}
func (UnimplementedAdminServer) GetNextComplaint(context.Context, *AdminEmpty) (*Complaint, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetNextComplaint not implemented")
}
func (UnimplementedAdminServer) DeleteComplaint(context.Context, *Complaint) (*AdminEmpty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteComplaint not implemented")
}
func (UnimplementedAdminServer) AcceptComplaint(context.Context, *Complaint) (*AdminEmpty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AcceptComplaint not implemented")
}
func (UnimplementedAdminServer) mustEmbedUnimplementedAdminServer() {}

// UnsafeAdminServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AdminServer will
// result in compilation errors.
type UnsafeAdminServer interface {
	mustEmbedUnimplementedAdminServer()
}

func RegisterAdminServer(s grpc.ServiceRegistrar, srv AdminServer) {
	s.RegisterService(&Admin_ServiceDesc, srv)
}

func _Admin_GetFeedbackStatistic_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AdminEmpty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdminServer).GetFeedbackStatistic(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Admin_GetFeedbackStatistic_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdminServer).GetFeedbackStatistic(ctx, req.(*AdminEmpty))
	}
	return interceptor(ctx, in, info, handler)
}

func _Admin_GetRecommendationStatistic_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AdminEmpty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdminServer).GetRecommendationStatistic(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Admin_GetRecommendationStatistic_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdminServer).GetRecommendationStatistic(ctx, req.(*AdminEmpty))
	}
	return interceptor(ctx, in, info, handler)
}

func _Admin_CreateFeedback_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Feedback)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdminServer).CreateFeedback(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Admin_CreateFeedback_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdminServer).CreateFeedback(ctx, req.(*Feedback))
	}
	return interceptor(ctx, in, info, handler)
}

func _Admin_CreateRecommendation_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Recommendation)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdminServer).CreateRecommendation(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Admin_CreateRecommendation_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdminServer).CreateRecommendation(ctx, req.(*Recommendation))
	}
	return interceptor(ctx, in, info, handler)
}

func _Admin_CreateFeedFeedback_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Recommendation)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdminServer).CreateFeedFeedback(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Admin_CreateFeedFeedback_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdminServer).CreateFeedFeedback(ctx, req.(*Recommendation))
	}
	return interceptor(ctx, in, info, handler)
}

func _Admin_GetNextComplaint_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AdminEmpty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdminServer).GetNextComplaint(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Admin_GetNextComplaint_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdminServer).GetNextComplaint(ctx, req.(*AdminEmpty))
	}
	return interceptor(ctx, in, info, handler)
}

func _Admin_DeleteComplaint_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Complaint)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdminServer).DeleteComplaint(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Admin_DeleteComplaint_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdminServer).DeleteComplaint(ctx, req.(*Complaint))
	}
	return interceptor(ctx, in, info, handler)
}

func _Admin_AcceptComplaint_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Complaint)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdminServer).AcceptComplaint(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Admin_AcceptComplaint_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdminServer).AcceptComplaint(ctx, req.(*Complaint))
	}
	return interceptor(ctx, in, info, handler)
}

// Admin_ServiceDesc is the grpc.ServiceDesc for Admin service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Admin_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "proto.Admin",
	HandlerType: (*AdminServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetFeedbackStatistic",
			Handler:    _Admin_GetFeedbackStatistic_Handler,
		},
		{
			MethodName: "GetRecommendationStatistic",
			Handler:    _Admin_GetRecommendationStatistic_Handler,
		},
		{
			MethodName: "CreateFeedback",
			Handler:    _Admin_CreateFeedback_Handler,
		},
		{
			MethodName: "CreateRecommendation",
			Handler:    _Admin_CreateRecommendation_Handler,
		},
		{
			MethodName: "CreateFeedFeedback",
			Handler:    _Admin_CreateFeedFeedback_Handler,
		},
		{
			MethodName: "GetNextComplaint",
			Handler:    _Admin_GetNextComplaint_Handler,
		},
		{
			MethodName: "DeleteComplaint",
			Handler:    _Admin_DeleteComplaint_Handler,
		},
		{
			MethodName: "AcceptComplaint",
			Handler:    _Admin_AcceptComplaint_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "admin.proto",
}
